name: Run API Tests

on:
  repository_dispatch:
    types: [run-api-tests]

jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      - name: Print image info
        run: |
          echo "Running API tests against image:"

      - name: Simulate API test suite
        run: |
          echo "Pulling image..."
          docker pull ${{ github.event.client_payload.image }}
          
          echo "Starting container..."
          docker run -d -p 8080:8080 --name api-test ${{ github.event.client_payload.image }}

          echo "Running tests..."
          sleep 5
          curl --fail http://localhost:8080/api/v1/hello
          curl --fail "http://localhost:8080/api/v1/sum?a=2&b=3"
          
          echo "Tests passed"

      - name: Clean up
        if: always()
        run: docker rm -f api-test || true
